# Changes to Spring Data REST's settings
spring:
  data:
    rest:
      basePath: /api

zuul:
  routes:
    api:
      path: /api/**
      url: http://localhost:9000
      stripPrefix: false
    fileupload:
      path: /upload/**
      url: http://localhost:7000
      stripPrefix: false
    filereader:
      path: /files/**
      url: http://localhost:7000
      stripPrefix: false



